### ISSUE TITLE
3.0 Small To-do Tips

### ISSUE THREAD

**Issue by xiazeyu** [EYHN/hexo-helper-live2d#42]
- [x] add these two links to document, so that users can check whether their browsers support WebGL.
#40 增加更多console，在代码中实现对检测浏览器是否支持webgl。
https://get.webgl.org/
- [x] doc: https://github.com/EYHN/hexo-helper-live2d/blob/master/CONTRIBUTING.md 中仅更新版本时使用`npm run changelog`
- [x] doc: https://github.com/EYHN/hexo-helper-live2d/blob/master/CONTRIBUTING.md 中修改带有歧义的 2. Make changes: clientJs only (serverJs skip)
- [x] 将device.js同时加入dependeicies和devdependices
- [x] use `git pull --tag` or sth., instead of just `git pull` may have better support on tags.
- [x] chore: index.js 中更好的检测device.js 脚本是否存在的实现 
```js
function loadlive2d(id,modelurl,headPos) {
    head_pos = typeof headPos === 'undefined' ? 0.5 : headPos;
    initL2dCanvas(id);
    init(modelurl);
}
```
- [x] `window.loadlive2d = loadlive2d;` at 427 line. in https://github.com/EYHN/hexo-helper-live2d/blob/master/src/main.js What does this code mean???
- [x] does transformRect mean 鼠标事件？
- [x] what does `deviceToScreen` mean?
- [x] http://makaidong.com/kakinuma/171758_571358.html
- [x] https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener
- [x] `headPos` ???
- [x] device.js 编译时将版本号加入insert.html 使得 `npm run rel` 时 `bundle.js`与`device.min.js`在html中同时具有版本号
- [x] chore: 对照UgilyJs中的蜜汁WARNING修改代码
- [x] chore: index.js 中代码注释
- [x] chore: 注释注释注释！

**Comment by xiazeyu** [comment]
- [ ] chore: index.js 中代码注释
- [ ] chore: index.js 中更好的检测device.js 脚本是否存在的实现
- [ ] doc: https://github.com/EYHN/hexo-helper-live2d/blob/master/CONTRIBUTING.md 中仅更新版本时使用`npm run changelog`

**Comment by xiazeyu** [comment]
- [ ] doc: https://github.com/EYHN/hexo-helper-live2d/blob/master/CONTRIBUTING.md 中修改带有歧义的 2. Make changes: clientJs only (serverJs skip)
- [ ] chore: 对照UgilyJs中的蜜汁WARNING修改代码
- [ ] device.js 编译时将版本号加入insert.html 使得 `npm run rel` 时 `bundle.js`与`device.min.js`在html中同时具有版本号

**Comment by xiazeyu** [comment]
- [ ] 将device.js同时加入dependeicies和devdependices
- [ ] use `git pull --tag` or sth., instead of just `git pull` may have better support on tags.

**Comment by xiazeyu** [comment]
- chore: index.js 中更好的检测device.js 脚本是否存在的实现 
```js
function loadlive2d(id,modelurl,headPos) {
    head_pos = typeof headPos === 'undefined' ? 0.5 : headPos;
    initL2dCanvas(id);
    init(modelurl);
}
```

**Comment by xiazeyu** [comment]
@EYHN `window.loadlive2d = loadlive2d;` at 427 line. in https://github.com/EYHN/hexo-helper-live2d/blob/master/src/main.js WTF is this code???

**Comment by xiazeyu** [comment]
http://makaidong.com/kakinuma/171758_571358.html

**Comment by xiazeyu** [comment]
does transformRect mean 鼠标事件？
what does `deviceToScreen` mean?

**Comment by xiazeyu** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener

**Comment by xiazeyu** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener

**Comment by xiazeyu** [comment]
`headPos` ???
- [ ] chore: 注释注释注释！

**Comment by xiazeyu** [comment]
https://github.com/EYHN/hexo-helper-live2d/blob/master/index.js#L50:L55
多余代码可删除
